#!/usr/bin/env python
"""Undermountain Startup Script"""
from mud.game import Game
import gevent
import logging
import sys
import settings


def get_python_version():
    major, minor, micro, _, _ = sys.version_info
    return '.'.join(map(str, [major, minor, micro]))


def display_banner():
    banner_lines = ("""\
      __ _______
     /  /       \ """ + (64 * "-") + """
    /  /  /  /  /    Undermountain Python MUD Server v{} - Python v{}
    \____/__/__/ """ + (66 * "-") + "\n").format(
        Game.VERSION,
        get_python_version(),
    ).split("\n")

    for line in banner_lines:
        logging.info(line)


def start_game():
    Game.VERSION = open("VERSION", "r").read().strip()
    display_banner()

    logging.info("Loaded settings from {}".format(settings.__file__))

    GAME = Game()
    try:
        task = gevent.spawn(GAME.start)
        task.join()
    except KeyboardInterrupt:
        GAME.stop()


def display_help():
    display_banner()
    [logging.info(line) for line in [
        "Commands:",
        "./um start - Start the game",
        "./um backup [id] - Backup data with identifier",
        "./um restore <id> - Restore data with identifier",
        "",
        "For backups, see the 'backups' folder",
    ]]
    sys.exit(1)


ARGS = sys.argv
if len(ARGS) == 1:
    display_help()
elif ARGS[1] == "start":
    start_game()
else:
    display_help()
